---
- summary: |
    Тестирование поиска товаров
  status: pass
---
- summary: |
    Фильтрация товаров
  status: pass
---
- summary: |
    Просмотр подробной информации о товаре
  status: pass
---
- summary: |
    Добавление товаров в корзину
  status: fail
---
- summary: |
    Безопасность данных
  status: fail
---
- summary: |
    Мобильная версия сайта
  status: fail
---
- summary: |
    Совместимость с браузерами
  status: fail
  ---
- summary: |
    Нагрузочное тестирование
  status: fail
