---
- summary: |
    Тестирование поиска товаров
  requirement: |
    Поиск товаров: Пользователи должны иметь возможность вводить ключевые слова или выбирать категории для поиска нужных товаров.
  description: |
    Проверить корректность работы функции поиска товаров по ключевым словам и категориям.
    steps:
      - Открыть главную страницу сайта.
        expected_result: Главная страница открыта.
        
      - Ввести в поле поиска название товара (например, \"dior\").
        expected_result: Поле поиска заполнено названием товара.
        
      - Нажать кнопку "Поиск"
        expected_result: Отображается список релевантных товаров.
        
      - Выбрать категорию из выпадающего списка (например, \"beauty\").
        expected_result: Категория выбрана.
        
      - Нажать кнопку "Применить фильтр"
        expected_result: Отображаются только те товары, которые соответствуют выбранной категории.

expected_results:
    - После ввода названия товара и нажатия кнопки "Поиск" отображается список релевантных товаров
    - После выбора категории и применения фильтра отображаются только те товары, которые соответствуют выбранной категории
  ---
  - summary: |
    Фильтрация товаров
  requirement: |
    Фильтры: Пользователи должны иметь возможность фильтровать товары по различным параметрам (цена, бренд)
  description: |
    Убедиться, что пользователь может успешно применять фильтры для сужения результатов поиска.
    steps:
      - Перейти на страницу каталога товаров.
        expected_result: Страница каталога товаров открыта.
      
      - Применить фильтр по цене (например, от 5 до 40 долларов).
        expected_result: Отображаются только товары в указанном ценовом диапазоне.
      
      - Применить фильтр по бренду (например, выбрать конкретный бренд).
        expected_result: Отображаются только товары выбранного бренда.

expected_results:
    - Отображены только те товары, которые соответствуют выбранным критериям фильтров
    - Товары без скидки не должны появляться при выборе опции отображаются только товары выбранного бренда
    
  ---
  
  - summary: |
    Просмотр подробной информации о товаре
  requirement: |
    Просмотр деталей товара: Пользователи должны иметь возможность просматривать полную информацию о товаре, включая описание, фотографии, характеристики и отзывы.
  description: |
    Проверка возможности просмотра полной информации о товаре после его выбора.
    steps:
      - Найти товар через поиск или каталог.
        expected_result: Товар найден.
      
      - Кликнуть на изображение или название товара.
        expected_result: Открывается страница с подробной информацией о товаре.
      
      - Проверить наличие описания товара, фотографий, характеристик, отзывов пользователей.
        expected_result: На странице присутствуют описание товара, фотографии, характеристики и отзывы пользователей.

expected_results:
    - На странице товара должна быть представлена полная информация: описание, фотографии, характеристики, отзывы
    - Информация должна быть структурирована и легко читаема
  ---
  - summary: |
    Добавление товаров в корзину
  requirement: |
    Корзина покупок: Пользователи должны иметь возможность добавлять товары в корзину, изменять их количество и удалять из корзины.
  description: |
    Убедиться, что пользователи могут добавлять товары в корзину и просматривать её содержимое.
    steps:
      - Выбрать любой товар из каталога.
        expected_result: Товар выбран.
      
      - Нажать кнопку "Добавить в корзину"
        expected_result: Товар добавлен в корзину.
      
      - Перейти в раздел "Корзина"
        expected_result: Раздел "Корзина" открыт.
      
      - Проверить, что добавленный товар присутствует в корзине.
        expected_result: Добавленный товар отображается в корзине.
      
      - Изменить количество товара в корзине (увеличить/уменьшить).
        expected_result: Количество товара изменяется корректно.
      
      - Удалить товар из корзины.
        expected_result: Товар удалён из корзины.

        
expected_results:
    - При нажатии на кнопку "Добавить в корзину" товар добавляется в корзину
    - В разделе "Корзина" отображается правильный список товаров с возможностью изменения количества и удаления
    - Обновлённое количество товара и итоговая сумма пересчитываются автоматически
    ---
    - summary: |
    Безопасность данных
  requirement: |
    Проверить безопасность передачи данных и защиту личной информации пользователя.
  description: |
    Безопасность: Сайт должен обеспечивать защиту персональных данных пользователей, использовать HTTPS для передачи конфиденциальной информации.
    - Проверка защищенного соединения при регистрации
    steps:
      - Открыть страницу регистрации
        expected_result: Страница открыта и доступна
      - Заполнить форму регистрации реальными данными
        expected_result: Форма заполнена корректно
      - Нажать кнопку 'Зарегистрироваться
        expected_result: Пользователь успешно зарегистрирован
      - Проверить URL страницы
        expected_result: Протокол HTTPS используется

  - Проверка защищенного соединения при входе
    steps:
      - Открыть страницу авторизации
        expected_result: Страница открыта и доступна
      - Ввести логин и пароль
        expected_result: Данные введены корректно
      - Нажать кнопку "Войти"
        expected_result: Пользователь успешно вошел в систему
      - Проверить URL страницы"
        expected_result: Протокол HTTPS используется

  - Проверка защищенного соединения при изменении личных данных
    steps:
      - Перейти в личный кабинет
        expected_result: Кабинет открыт и доступен
      - Найти раздел редактирования профиля
        expected_result: Раздел найден и доступен
      - Изменить адрес доставки и/или номер телефона
        expected_result: Изменения внесены корректно
      - Сохранить изменения
        expected_result: Изменения сохранены успешно
      - Проверить URL страницы
        expected_result: Протокол HTTPS используется

  - Проверка защищенного соединения при оформлении заказа
    steps:
      - Добавить товар в корзину
        expected_result: Товар добавлен в корзину
      - Перейти к оформлению заказа
        expected_result: Процесс оформления заказа начат
      - На этапе ввода платежных данных проверить URL страницы
        expected_result: Протокол HTTPS используется
      - Завершить оформление заказа
        expected_result: Заказ оформлен успешно

expected_results:
  - Все страницы, связанные с передачей личных данных, используют защищённое соединение HTTPS
  - Личные данные пользователя защищены и недоступны третьим лицам
  - Платежные данные передаются через безопасное соединение и шифруются
  
  ---
  - summary: |
    Мобильная версия сайта
  requirement: |
    Убедиться, что сайт адаптирован для мобильных устройств и удобен для использования на смартфонах и планшетах.
  description: |
  Адаптация под мобильные устройства: Сайт должен корректно отображаться и функционировать на мобильных устройствах (смартфоны, планшеты).
  steps:
    - Открыть сайт на мобильном устройстве (смартфоне, планшете)
      expected_result: Сайт загружен и доступен на мобильном устройстве
    
    - Проверить навигацию по сайту
      expected_result: Навигационные элементы работают корректно, переходы осуществляются без ошибок
      
    - Использовать функцию поиска
      expected_result: Поиск работает корректно, результаты поиска отображаются правильно
      
    - Просмотреть карточку товара
      expected_result: Карточка товара отображается корректно, вся необходимая информация доступна
      
    - Добавить товар в корзину
      expected_result: Товар успешно добавлен в корзину, никаких ошибок не возникает
      
    - Оформить заказ
      expected_result: Процесс оформления заказа проходит без ошибок, все формы заполняются корректно
      
    - Провести тестирование на разных разрешениях экрана и ориентациях устройства (портретный и ландшафтный режимы)
      expected_result: Сайт адаптируется под разные разрешения и ориентации экрана, контент остается доступным и удобным

  expected_results:
    - Сайт корректно отображается на мобильных устройствах
    - Все элементы интерфейса доступны и удобны для взаимодействия
    - Функциональность сайта полностью сохранена и работает без ошибок

    ---

    - summary: |
    Совместимость с браузерами
  requirement: |
    Проверить работу сайта в последних версиях популярных браузеров.
  description: |
    Сайт должен поддерживать последние версии основных браузеров (Google Chrome, Mozilla Firefox, Safari, Microsoft Edge).
    steps:
    - Открыть сайт в Google Chrome
      expected_result: Сайт загружен и доступен в Google Chrome
    
    - Повторить основные сценарии использования сайта (поиск, фильтрация, добавление в корзину) в Google Chrome
      expected_result: Основные функции работают корректно, без визуальных и функциональных отклонений
      
    - Открыть сайт в Mozilla Firefox
      expected_result: Сайт загружен и доступен в Mozilla Firefox
    
    - Повторить основные сценарии использования сайта (поиск, фильтрация, добавление в корзину) в Mozilla Firefox
      expected_result: Основные функции работают корректно, без визуальных и функциональных отклонений
      
    - Открыть сайт в Safari
      expected_result: Сайт загружен и доступен в Safari
    
    - Повторить основные сценарии использования сайта (поиск, фильтрация, добавление в корзину) в Safari
      expected_result: Основные функции работают корректно, без визуальных и функциональных отклонений
      
    - Открыть сайт в Microsoft Edge
      expected_result: Сайт загружен и доступен в Microsoft Edge
    
    - action: Повторить основные сценарии использования сайта (поиск, фильтрация, добавление в корзину) в Microsoft Edge
      expected_result: Основные функции работают корректно, без визуальных и функциональных отклонений

  expected_results:
    - Сайт работает одинаково во всех указанных браузерах без визуальных и функциональных отклонений
    - Все элементы интерфейса правильно отображаются и работают как ожидается 
  ---
  

  
    
  
