---
- summary: |
    "Тестирование поиска товаров"
  requirement: |
    Поиск товаров: Пользователи должны иметь возможность вводить ключевые слова или выбирать категории для поиска нужных товаров.
  description: |
    "Проверить корректность работы функции поиска товаров по ключевым словам и категориям."
    steps:
      - action: "Открыть главную страницу сайта."
        expected_result: "Главная страница открыта."
        
      - action: "Ввести в поле поиска название товара (например, \"dior\")."
        expected_result: "Поле поиска заполнено названием товара."
        
      - action: "Нажать кнопку \"Поиск\""
        expected_result: "Отображается список релевантных товаров."
        
      - action: "Выбрать категорию из выпадающего списка (например, \"beauty\")."
        expected_result: "Категория выбрана."
        
      - action: "Нажать кнопку \"Применить фильтр\""
        expected_result: "Отображаются только те товары, которые соответствуют выбранной категории."
  ---
  - summary: |
    "Фильтрация товаров"
  requirement: |
    Фильтры: Пользователи должны иметь возможность фильтровать товары по различным параметрам (цена, бренд)
  description: |
    "Убедиться, что пользователь может успешно применять фильтры для сужения результатов поиска."
    steps:
      - action: "Перейти на страницу каталога товаров."
        expected_result: "Страница каталога товаров открыта."
      
      - action: "Применить фильтр по цене (например, от 5 до 40 долларов)."
        expected_result: "Отображаются только товары в указанном ценовом диапазоне."
      
      - action: "Применить фильтр по бренду (например, выбрать конкретный бренд)."
        expected_result: "Отображаются только товары выбранного бренда."
  ---
  
  - summary: |
    "Просмотр подробной информации о товаре"
  requirement: |
    Просмотр деталей товара: Пользователи должны иметь возможность просматривать полную информацию о товаре, включая описание, фотографии, характеристики и отзывы.
  description: |
    "Проверка возможности просмотра полной информации о товаре после его выбора."
    steps:
      - action: "Найти товар через поиск или каталог."
        expected_result: "Товар найден."
      
      - action: "Кликнуть на изображение или название товара."
        expected_result: "Открывается страница с подробной информацией о товаре."
      
      - action: "Проверить наличие описания товара, фотографий, характеристик, отзывов пользователей."
        expected_result: "На странице присутствуют описание товара, фотографии, характеристики и отзывы пользователей."
  ---
  - summary: |
    "Добавление товаров в корзину"
  requirement: |
    Корзина покупок: Пользователи должны иметь возможность добавлять товары в корзину, изменять их количество и удалять из корзины.
  description: |
    "Убедиться, что пользователи могут добавлять товары в корзину и просматривать её содержимое."
    steps:
      - action: "Выбрать любой товар из каталога."
        expected_result: "Товар выбран."
      
      - action: "Нажать кнопку \"Добавить в корзину\"."
        expected_result: "Товар добавлен в корзину."
      
      - action: "Перейти в раздел \"Корзина\"."
        expected_result: "Раздел \"Корзина\" открыт."
      
      - action: "Проверить, что добавленный товар присутствует в корзине."
        expected_result: "Добавленный товар отображается в корзине."
      
      - action: "Изменить количество товара в корзине (увеличить/уменьшить)."
        expected_result: "Количество товара изменяется корректно."
      
      - action: "Удалить товар из корзины."
        expected_result: "Товар удалён из корзины."
    ---
    - summary: |
    "Добавление товаров в корзину"
  requirement: |
    Корзина покупок: Пользователи должны иметь возможность добавлять товары в корзину, изменять их количество и удалять из корзины.
  description: |
    "Убедиться, что пользователи могут добавлять товары в корзину и просматривать её содержимое."
    
  
