---
summary: |
  Тестирование поиска товаров
requirement: >
  Пользователи должны иметь возможность вводить ключевые слова или
  выбирать категории для поиска нужных товаров.
description: >
  Проверить корректность работы функции поиска товаров по ключевым
  словам и категориям.
prerequisites: |
  Открыта главная страница сайта.
test-data: |
  Название товара: dior
  Категория: beauty
steps: null -Ввести в поле поиска название товара (например, "dior") -Нажать
  кнопку "Поиск" -Выбрать категорию из выпадающего списка (например, "beauty")
  -Нажать кнопку "Применить фильтр"
expected-result: >
  -Отображается список релевантных товаров после ввода названия
expected_results:
    - После ввода названия товара и нажатия кнопки "Поиск" отображается список релевантных товаров
    - После выбора категории и применения фильтра отображаются только те товары, которые соответствуют выбранной категории
  ---
summary: |
  Фильтрация товаров
requirement: >
  Пользователи должны иметь возможность фильтровать товары по
  различным параметрам (цена, бренд).
description: >
  Убедиться, что пользователь может успешно применять фильтры для
  сужения результатов поиска.
prerequisites: |
  Открыта страница каталога товаров.
test-data: |
  Ценовой диапазон: от 5 до 40 долларов
  Бренд: Calvin Klein
steps: -Применить фильтр по цене (например, от 5 до 40 долларов) -Применить
  фильтр по бренду (например, выбрать конкретный бренд)
expected-result: >
  -Отображаются только те товары, которые соответствуют выбранным
  критериям фильтров.
  ---
summary: |
  Просмотр подробной информации о товаре
requirement: >
  Пользователи должны иметь возможность просматривать полную
  информацию о товаре, включая описание, фотографии, характеристики и отзывы.
description: |
  Проверка возможности просмотра полной информации о товаре после его выбора.
prerequisites: |
  Товар найден через поиск или каталог.
steps: -Кликнуть на изображение или название товара. -Проверить наличие описания
  товара, фотографий, характеристик, отзывов пользователей.
expected-result: >
  -Открывается страница с подробной информацией о товаре.
  -На странице присутствуют описание товара, фотографии, характеристики и отзывы пользователей.
---
summary: |
  Добавление товаров в корзину
requirement: >
  Пользователи должны иметь возможность добавлять товары в корзину,
  изменять их количество и удалять из корзины.
description: >
  Убедиться, что пользователи могут добавлять товары в корзину и
  просматривать её содержимое.
prerequisites: |
  Любой товар выбран из каталога.
steps: -Нажать кнопку "Добавить в корзину" -Перейти в раздел "Корзина"
  -Проверить, что добавленный товар присутствует в корзине. -Изменить количество
  товара в корзине (увеличить/уменьшить). -Удалить товар из корзины.
expected-result: |
  -Товар добавлен в корзину.
  -Раздел "Корзина" открыт.
  -Добавленный товар отображается в корзине.
  -Количество товара изменяется корректно.
  -Товар удалён из корзины.
  ---
summary: |
  Проверка безопасности сайта
requirement: |
  Сайт должен быть безопасным и защищать данные пользователя.
description: >
  Проверить использование безопасного соединения HTTPS, защиту от
  SQL-инъекций и XSS-атак, обработку ошибок и актуальность сертификатов SSL/TLS.
prerequisites: |
  Открыть главную страницу сайта.
steps: -Проверить, что используется протокол HTTPS -Выполнить попытку
  SQL-инъекции в форме поиска -Проверить актуальность сертификатов SSL/TLS
expected-result: |
  -Использует HTTPS
  -Не позволяет выполнить SQL-инъекцию
  -Сертификаты SSL/TLS являются актуальными
expected_results: -Протокол HTTPS используется для защиты данных -Защита от
  SQL-инъекций работает -Сертификаты SSL/TLS актуальны
---
summary: |
  Мобильная версия сайта
requirement: >
  Сайт должен иметь мобильную версию, обеспечивающую удобный доступ и
  взаимодействие с сайтом на мобильных устройствах.
description: >
  Проверка наличия мобильной версии сайта и её доступности
  пользователям с мобильных устройств.
prerequisites: |
  Доступ к интернету с мобильного устройства (смартфона, планшета).
steps: -Открыть сайт на мобильном устройстве
expected_result: Загрузка сайта завершена, сайт открывается на мобильном
  устройстве. -Проверить наличие мобильной версии сайта -Появляется уведомление
  о наличии мобильной версии или ссылка на неё. -Перейти на мобильную версию
  сайта -Переход на мобильную версию выполнен, интерфейс адаптирован под
  мобильное устройство. -Работа мобильной версии сайта -Убедиться, что мобильная
  версия сайта функционирует корректно и предоставляет аналогичный функционал
  основной версии сайта -Проверка корректности работы мобильной версии сайта,
  включая функциональность поиска, навигации, добавления товаров в корзину и
  оформления заказов. -Открытие мобильной версии сайта. -Проверить навигацию по
  сайту -Элементы навигации работают корректно, переходы осуществляются без
  ошибок. -Использовать функцию поиска -Поиск работает корректно, результаты
  поиска отображаются правильно. -Просмотреть карточку товара -Карточка товара
  отображается корректно, вся необходимая информация доступна. -Добавить товар в
  корзину -Товар успешно добавлен в корзину, никаких ошибок не возникает.
  -Оформить заказ -Процесс оформления заказа проходит без ошибок, все формы
  заполняются корректно. -Провести тестирование на разных разрешениях экрана и
  ориентациях устройства (портретный и ландшафтный режимы) -Сайт адаптируется
  под различные размеры и ориентации экрана, контент остаётся доступным и
  удобным.
expected_results: -Сайт корректно отображается на мобильных устройствах -Все
  элементы интерфейса доступны и удобны для использования -Функциональность
  сайта полностью сохранена и работает без ошибок
   ---
summary: |
  Совместимость с браузерами
requirement: >
  Проверить работу сайта в последних версиях популярных браузеров
  (Google Chrome, Mozilla Firefox, Safari, Microsoft Edge).
description: >
  Сайт должен поддерживать последние версии основных браузеров
  (Google Chrome, Mozilla Firefox, Safari, Microsoft Edge).
steps: -Открыть сайт в Google Chrome -Повторить основные сценарии использования
  сайта (поиск, фильтрация, добавление в корзину) в Google Chrome -Открыть сайт
  в Mozilla Firefox -Повторить основные сценарии использования сайта (поиск,
  фильтрация, добавление в корзину) в Mozilla Firefox -Открыть сайт в Safari
  -Повторить основные сценарии использования сайта (поиск, фильтрация,
  добавление в корзину) в Safari -Открыть сайт в Microsoft Edge -Повторить
  основные сценарии использования сайта (поиск, фильтрация, добавление в
  корзину) в Microsoft Edge
expected_result: Основные функции работают корректно, без визуальных и
  функциональных отклонений.
expected_results: -Сайт работает одинаково во всех указанных браузерах без
  визуальных и функциональных отклонений. -Все элементы интерфейса правильно
  отображаются и работают как ожидается.
   ---
summary: |
  Нагрузочное тестирование
requirement: >
  Убедиться, что сайт способен обрабатывать большое количество
  одновременных запросов без снижения производительности и отказов.
description: >
  Оценить способность сайта выдерживать высокую нагрузку (большое
  количество одновременных запросов).
preconditions: -Сайт доступен и работает корректно при нормальной нагрузке.
  -Тестовая среда настроена и готова к проведению тестов.
steps: -Подготовьте инструменты для генерации нагрузки (например, JMeter).
  -Настройте сценарий нагрузки с учётом ожидаемого количества пользователей и
  типов запросов. -Запустите тестовый сценарий и начните генерировать нагрузку.
  -Мониторинг ключевых метрик во время теста (время отклика, количество ошибок,
  использование ресурсов сервера).
expected_results: -Время отклика не превышает допустимых значений даже под
  высокой нагрузкой. -Количество ошибок остается минимальным или отсутствует
  совсем. -Ресурсы сервера (ЦП, память, диск) используются эффективно и не
  перегружены.
postconditions: -Проведите анализ результатов и составите отчёт о проведённом
  тестировании. -При необходимости внесите изменения в инфраструктуру или код
  для улучшения устойчивости к высоким нагрузкам.
