---
- summary: |
    "Тестирование поиска товаров"
  requirement: |
    Поиск товаров: Пользователи должны иметь возможность вводить ключевые слова или выбирать категории для поиска нужных товаров.
  description: |
    "Проверить корректность работы функции поиска товаров по ключевым словам и категориям."
    steps:
      - action: "Открыть главную страницу сайта."
        expected_result: "Главная страница открыта."
        
      - action: "Ввести в поле поиска название товара (например, \"dior\")."
        expected_result: "Поле поиска заполнено названием товара."
        
      - action: "Нажать кнопку \"Поиск\""
        expected_result: "Отображается список релевантных товаров."
        
      - action: "Выбрать категорию из выпадающего списка (например, \"beauty\")."
        expected_result: "Категория выбрана."
        
      - action: "Нажать кнопку \"Применить фильтр\""
        expected_result: "Отображаются только те товары, которые соответствуют выбранной категории."

expected_results:
    - "После ввода названия товара и нажатия кнопки 'Поиск' отображается список релевантных товаров"
    - "После выбора категории и применения фильтра отображаются только те товары, которые соответствуют выбранной категории"
  ---
  - summary: |
    "Фильтрация товаров"
  requirement: |
    Фильтры: Пользователи должны иметь возможность фильтровать товары по различным параметрам (цена, бренд)
  description: |
    "Убедиться, что пользователь может успешно применять фильтры для сужения результатов поиска."
    steps:
      - action: "Перейти на страницу каталога товаров."
        expected_result: "Страница каталога товаров открыта."
      
      - action: "Применить фильтр по цене (например, от 5 до 40 долларов)."
        expected_result: "Отображаются только товары в указанном ценовом диапазоне."
      
      - action: "Применить фильтр по бренду (например, выбрать конкретный бренд)."
        expected_result: "Отображаются только товары выбранного бренда."

expected_results:
    - "Отображены только те товары, которые соответствуют выбранным критериям фильтров"
    - "Товары без скидки не должны появляться при выборе опции 'Отображаются только товары выбранного бренда'"
    
  ---
  
  - summary: |
    "Просмотр подробной информации о товаре"
  requirement: |
    Просмотр деталей товара: Пользователи должны иметь возможность просматривать полную информацию о товаре, включая описание, фотографии, характеристики и отзывы.
  description: |
    "Проверка возможности просмотра полной информации о товаре после его выбора."
    steps:
      - action: "Найти товар через поиск или каталог."
        expected_result: "Товар найден."
      
      - action: "Кликнуть на изображение или название товара."
        expected_result: "Открывается страница с подробной информацией о товаре."
      
      - action: "Проверить наличие описания товара, фотографий, характеристик, отзывов пользователей."
        expected_result: "На странице присутствуют описание товара, фотографии, характеристики и отзывы пользователей."

expected_results:
    - "На странице товара должна быть представлена полная информация: описание, фотографии, характеристики, отзывы"
    - "Информация должна быть структурирована и легко читаема"
  ---
  - summary: |
    "Добавление товаров в корзину"
  requirement: |
    Корзина покупок: Пользователи должны иметь возможность добавлять товары в корзину, изменять их количество и удалять из корзины.
  description: |
    "Убедиться, что пользователи могут добавлять товары в корзину и просматривать её содержимое."
    steps:
      - action: "Выбрать любой товар из каталога."
        expected_result: "Товар выбран."
      
      - action: "Нажать кнопку \"Добавить в корзину\"."
        expected_result: "Товар добавлен в корзину."
      
      - action: "Перейти в раздел \"Корзина\"."
        expected_result: "Раздел \"Корзина\" открыт."
      
      - action: "Проверить, что добавленный товар присутствует в корзине."
        expected_result: "Добавленный товар отображается в корзине."
      
      - action: "Изменить количество товара в корзине (увеличить/уменьшить)."
        expected_result: "Количество товара изменяется корректно."
      
      - action: "Удалить товар из корзины."
        expected_result: "Товар удалён из корзины."

        
expected_results:
    - "При нажатии на кнопку 'Добавить в корзину' товар добавляется в корзину"
    - "В разделе 'Корзина' отображается правильный список товаров с возможностью изменения количества и удаления"
    - "Обновлённое количество товара и итоговая сумма пересчитываются автоматически"
    ---
    - summary: |
    "Безопасность данных"
  requirement: |
    Проверить безопасность передачи данных и защиту личной информации пользователя.
  description: |
    Безопасность: Сайт должен обеспечивать защиту персональных данных пользователей, использовать HTTPS для передачи конфиденциальной информации.
    - name: "Проверка защищенного соединения при регистрации"
    steps:
      - action: "Открыть страницу регистрации"
        expected_result: "Страница открыта и доступна"
      - action: "Заполнить форму регистрации реальными данными"
        expected_result: "Форма заполнена корректно"
      - action: "Нажать кнопку 'Зарегистрироваться'"
        expected_result: "Пользователь успешно зарегистрирован"
      - action: "Проверить URL страницы"
        expected_result: "Протокол HTTPS используется"

  - name: "Проверка защищенного соединения при входе"
    steps:
      - action: "Открыть страницу авторизации"
        expected_result: "Страница открыта и доступна"
      - action: "Ввести логин и пароль"
        expected_result: "Данные введены корректно"
      - action: "Нажать кнопку 'Войти'"
        expected_result: "Пользователь успешно вошел в систему"
      - action: "Проверить URL страницы"
        expected_result: "Протокол HTTPS используется"

  - name: "Проверка защищенного соединения при изменении личных данных"
    steps:
      - action: "Перейти в личный кабинет"
        expected_result: "Кабинет открыт и доступен"
      - action: "Найти раздел редактирования профиля"
        expected_result: "Раздел найден и доступен"
      - action: "Изменить адрес доставки и/или номер телефона"
        expected_result: "Изменения внесены корректно"
      - action: "Сохранить изменения"
        expected_result: "Изменения сохранены успешно"
      - action: "Проверить URL страницы"
        expected_result: "Протокол HTTPS используется"

  - name: "Проверка защищенного соединения при оформлении заказа"
    steps:
      - action: "Добавить товар в корзину"
        expected_result: "Товар добавлен в корзину"
      - action: "Перейти к оформлению заказа"
        expected_result: "Процесс оформления заказа начат"
      - action: "На этапе ввода платежных данных проверить URL страницы"
        expected_result: "Протокол HTTPS используется"
      - action: "Завершить оформление заказа"
        expected_result: "Заказ оформлен успешно"

expected_results:
  - "Все страницы, связанные с передачей личных данных, используют защищённое соединение (HTTPS)"
  - "Личные данные пользователя защищены и недоступны третьим лицам"
  - "Платежные данные передаются через безопасное соединение и шифруются"
  
  ---
  - summary: |
    "Мобильная версия сайта"
  requirement: |
    "Убедиться, что сайт адаптирован для мобильных устройств и удобен для использования на смартфонах и планшетах."
  description: |
  Адаптация под мобильные устройства: Сайт должен корректно отображаться и функционировать на мобильных устройствах (смартфоны, планшеты).
  steps:
    - action: "Открыть сайт на мобильном устройстве (смартфоне, планшете)"
      expected_result: "Сайт загружен и доступен на мобильном устройстве"
    
    - action: "Проверить навигацию по сайту"
      expected_result: "Навигационные элементы работают корректно, переходы осуществляются без ошибок"
      
    - action: "Использовать функцию поиска"
      expected_result: "Поиск работает корректно, результаты поиска отображаются правильно"
      
    - action: "Просмотреть карточку товара"
      expected_result: "Карточка товара отображается корректно, вся необходимая информация доступна"
      
    - action: "Добавить товар в корзину"
      expected_result: "Товар успешно добавлен в корзину, никаких ошибок не возникает"
      
    - action: "Оформить заказ"
      expected_result: "Процесс оформления заказа проходит без ошибок, все формы заполняются корректно"
      
    - action: "Провести тестирование на разных разрешениях экрана и ориентациях устройства (портретный и ландшафтный режимы)"
      expected_result: "Сайт адаптируется под разные разрешения и ориентации экрана, контент остается доступным и удобным"

  expected_results:
    - "Сайт корректно отображается на мобильных устройствах"
    - "Все элементы интерфейса доступны и удобны для взаимодействия"
    - "Функциональность сайта полностью сохранена и работает без ошибок"

    ---

    - summary: |
    "Совместимость с браузерами"
  requirement: |
    "Проверить работу сайта в последних версиях популярных браузеров."
  description: |
    Сайт должен поддерживать последние версии основных браузеров (Google Chrome, Mozilla Firefox, Safari, Microsoft Edge).
    steps:
    - action: "Открыть сайт в Google Chrome"
      expected_result: "Сайт загружен и доступен в Google Chrome"
    
    - action: "Повторить основные сценарии использования сайта (поиск, фильтрация, добавление в корзину) в Google Chrome"
      expected_result: "Основные функции работают корректно, без визуальных и функциональных отклонений"
      
    - action: "Открыть сайт в Mozilla Firefox"
      expected_result: "Сайт загружен и доступен в Mozilla Firefox"
    
    - action: "Повторить основные сценарии использования сайта (поиск, фильтрация, добавление в корзину) в Mozilla Firefox"
      expected_result: "Основные функции работают корректно, без визуальных и функциональных отклонений"
      
    - action: "Открыть сайт в Safari"
      expected_result: "Сайт загружен и доступен в Safari"
    
    - action: "Повторить основные сценарии использования сайта (поиск, фильтрация, добавление в корзину) в Safari"
      expected_result: "Основные функции работают корректно, без визуальных и функциональных отклонений"
      
    - action: "Открыть сайт в Microsoft Edge"
      expected_result: "Сайт загружен и доступен в Microsoft Edge"
    
    - action: "Повторить основные сценарии использования сайта (поиск, фильтрация, добавление в корзину) в Microsoft Edge"
      expected_result: "Основные функции работают корректно, без визуальных и функциональных отклонений"

  expected_results:
    - "Сайт работает одинаково во всех указанных браузерах без визуальных и функциональных отклонений"
    - "Все элементы интерфейса правильно отображаются и работают как ожидается"  
  ---

  
    
  
