---
functional:
- Пользователи должны иметь возможность вводить ключевые слова или выбирать категории для поиска нужных товаров.
- Пользователи должны иметь возможность фильтровать товары по различным параметрам (цена, бренд, наличие скидок и др.).
- Пользователи должны иметь возможность просматривать полную информацию о товаре, включая описание, фотографии, характеристики и отзывы.
- Пользователи должны иметь возможность добавлять товары в корзину, изменять их количество и удалять из корзины.
- Пользователи должны иметь возможность оформлять заказ, указывая адрес доставки и способ оплаты.

non-functional:
- Сайт должен обеспечивать защиту персональных данных пользователей, использовать HTTPS для передачи конфиденциальной информации.
- Сайт должен быстро загружаться и реагировать на запросы пользователей, даже при высоком трафике.
- Интерфейс сайта должен быть интуитивно понятен и удобен для пользователей всех уровней подготовки.
- Сайт должен корректно отображаться и функционировать на мобильных устройствах (смартфоны, планшеты).
- Сайт должен поддерживать последние версии основных браузеров (Google Chrome, Mozilla Firefox, Safari, Microsoft Edge).

implicit:
- Пользователи должны иметь возможность оставлять отзывы и получать обратную связь от службы поддержки.
- Навигация по сайту должна быть простой и понятной, чтобы пользователи могли легко находить нужные им товары и услуги.
- Информация на сайте должна регулярно обновляться, чтобы соответствовать текущему ассортименту и ценам.
- Сайт должен соответствовать всем законодательным нормам, касающимся защиты данных и прав потребителей.
