---
functional:
- Поиск товаров: Пользователи должны иметь возможность вводить ключевые слова или выбирать категории для поиска нужных товаров.
- Фильтры: Пользователи должны иметь возможность фильтровать товары по различным параметрам (цена, бренд, наличие скидок и др.).
- Просмотр деталей товара: Пользователи должны иметь возможность просматривать полную информацию о товаре, включая описание, фотографии, характеристики и отзывы.
- Корзина покупок: Пользователи должны иметь возможность добавлять товары в корзину, изменять их количество и удалять из корзины.
- Оформление заказа: Пользователи должны иметь возможность оформлять заказ, указывая адрес доставки и способ оплаты.

non-functional:
- Безопасность: Сайт должен обеспечивать защиту персональных данных пользователей, использовать HTTPS для передачи конфиденциальной информации.
- Производительность: Сайт должен быстро загружаться и реагировать на запросы пользователей, даже при высоком трафике.
- Удобство использования (Usability): Интерфейс сайта должен быть интуитивно понятен и удобен для пользователей всех уровней подготовки.
- Адаптация под мобильные устройства: Сайт должен корректно отображаться и функционировать на мобильных устройствах (смартфоны, планшеты).
- Совместимость с браузерами: Сайт должен поддерживать последние версии основных браузеров (Google Chrome, Mozilla Firefox, Safari, Microsoft Edge).

implicit:
- Обратная связь: Пользователи должны иметь возможность оставлять отзывы и получать обратную связь от службы поддержки.
- Интуитивность интерфейса: Навигация по сайту должна быть простой и понятной, чтобы пользователи могли легко находить нужные им товары и услуги.
- Актуальность контента: Информация на сайте должна регулярно обновляться, чтобы соответствовать текущему ассортименту и ценам.
- Соответствие законодательству: Сайт должен соответствовать всем законодательным нормам, касающимся защиты данных и прав потребителей.
